# Site settings
title: B.A.S.I.U.X.
email: caue@basiux.org
description: > Benevolent Artificial Super Intelligence User eXperience.
  Don't mind the mountain.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://basiux.org" # the base hostname & protocol for your site
twitter_username: basiux
github_username:  basiux

# Build settings
markdown: kramdown
